Turn one of the M9K shotguns into a low-damage, high-knockback gun
CFC-Servers/cfc_entity_stubber_build_kill pull request #22
Opened 2022-12-12 20:29 UTC by legokidlogan

2022-12-16 21:51 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/cfc_m9k/cfc9k_shotgun_bonk.lua
> +    hook.Add( "Think", "M9K_Stubber_BonkGun_DetectImpact", function()
shouldn't be on client

2022-12-16 21:51 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/cfc_m9k/cfc9k_shotgun_bonk.lua
> +    hook.Add( "EntityTakeDamage", "M9K_Stubber_BonkGun_YeetVictim", function( victim, dmg )
shouldn't be on client

2023-06-14 21:42 UTC, brandonsturgeon requested changes

2023-06-14 21:42 UTC, brandonsturgeon commented on lua/cfc_entity_stubber/cfc_m9k/cfc9k_bonk.lua
> +hook.Add( "EntityTakeDamage", "M9K_Stubber_Bonk_YeetVictim", function( victim, dmg )
Probably better in PostEntityTakeDamage?

2023-06-14 21:42 UTC, brandonsturgeon commented on lua/cfc_entity_stubber/cfc_m9k/cfc9k_bonk.lua
> +    if dot >= 0 then return Vector( 0, 0, 0 ) end
Localize this vector at the top if it won't be modified

2023-06-14 21:42 UTC, brandonsturgeon commented on lua/cfc_entity_stubber/cfc_m9k/cfc9k_bonk.lua
> +
Localize IsValid and prefer `:IsValid()`

2023-06-14 22:39 UTC, brandonsturgeon approved these changes

2023-06-14 22:41 UTC, merged