Remove ammotype reload
CFC-Servers/cfc_entity_stubber_build_kill pull request #43
Opened 2023-07-03 10:42 UTC by Deconkle

Tested locally, should work.

2023-07-07 10:49 UTC, brandonsturgeon requested changes
This is the right idea, but some of these attach and detach funcs have extra logic in them.

For example, in `am_flechetterounds.lua`:
```lua
function att:attachFunc()
    self.Shots = 20
    self:unloadWeapon()
end

function att:detachFunc()
    self.Shots = self.Shots_Orig
    self:unloadWeapon()
end
```

or `am_slugrounds.lua`:
```lua
  function att:attachFunc()
      self.Shots = 1
      self.ClumpSpread = nil
      self:unloadWeapon()
  end

  function att:detachFunc()
      self.Shots = self.Shots_Orig
      self.ClumpSpread = self.ClumpSpread_Orig
      self:unloadWeapon()
  end
```

So what we really want to do is make `unloadWeapon` not run when ammo types are attached/detached.

I think that would require a broader solution, maybe wrapping the top-level `unloadWeapon` function. Not sure yet.

For now, I'm okay with replicating the functions, sans `unloadWeapon`. My suggestions take care of all of the ones that have extra logic (many do not).

2023-07-07 10:49 UTC, brandonsturgeon commented on lua/cfc_entity_stubber/cw_attachment/am_flechetterounds.lua
> +    function attachment:detachFunc() end
```suggestion
    function attachment:attachFunc()
        self.Shots = 20
    end

    function attachment:detachFunc()
        self.Shots = self.Shots_Orig
    end

```

2023-07-07 10:49 UTC, brandonsturgeon commented on lua/cfc_entity_stubber/cw_attachment/am_slugrounds.lua
> +    function attachment:detachFunc() end
```suggestion
    function attachment:attachFunc()
        self.Shots = 1
        self.ClumpSpread = nil
    end

    function attachment:detachFunc()
        self.Shots = self.Shots_Orig
        self.ClumpSpread = self.ClumpSpread_Orig
    end

```

2023-07-08 12:49 UTC, wrefgtzweve commented
@CodiumAI-Agent

2023-07-08 12:49 UTC, CodiumAI-Agent commented
Preparing review...

2023-07-08 12:50 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** The PR is focused on removing the need for players to reload every weapon they have a preset for when they spawn. It also mitigates a bug where players had to reload twice before getting any ammo.
- 🔍 **Description and title:** Yes
- 📌 **Type of PR:** Bug fix
- 🧪 **Relevant tests added:** No
- ✨ **Minimal and focused:** Yes, the PR is focused on a single issue of reloading weapons and all changes are relevant to this issue.
- 🔒 **Security concerns:** No, the changes made in this PR do not introduce any apparent security concerns.
## PR Feedback

- 💡 **General PR suggestions:** The PR is generally well-structured and focused. However, it would be beneficial to add some tests to verify the new behavior and ensure that the bug has been fixed. Additionally, it would be helpful to add comments in the code explaining the purpose of the changes, especially for the `attachFunc` and `detachFunc` functions.

- 🤖 **Code suggestions:**


  - **relevant file:** am_flechetterounds.lua
   **suggestion content:** Consider adding a comment explaining why the `Shots` value is being set to 20 in the `attachFunc` and reset in the `detachFunc`. This will make the code more understandable for other developers. [medium]


  - **relevant file:** am_slugrounds.lua
   **suggestion content:** It would be helpful to add a comment explaining why `self.Shots` is set to 1 and `self.ClumpSpread` is set to `nil` in the `attachFunc`, and why they are reset in the `detachFunc`. This will make the code more understandable for other developers. [medium]


  - **relevant file:** am_magnum.lua
   **suggestion content:** The `attachFunc` and `detachFunc` functions are empty. If they are not needed, consider removing them to clean up the code. If they are needed for future use, add a comment explaining this. [medium]


  - **relevant file:** am_matchgrade.lua
   **suggestion content:** Similar to the `am_magnum.lua` file, the `attachFunc` and `detachFunc` functions are empty. Consider removing them if they are not needed, or add a comment explaining their purpose if they are needed for future use. [medium]


### How to use
> Tag me in a comment '@CodiumAI-Agent' to ask for a new review after you update the PR.
> You can also tag me and ask any question, for example '@CodiumAI-Agent is the PR ready for merge?'

2023-07-13 21:00 UTC, merged